name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: mahernoz
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: docker buildx build --platform windows/amd64 -t mahernoz/myapp:latest .
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

      - name: Push Docker image
        run: docker buildx build --platform windows/amd64 --push -t mahernoz/myapp:latest .
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
