Resources:
  TestCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: test-cluster

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecs-task-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskDefinition1:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: task-definition-1
      ContainerDefinitions:
        - Name: container-1
          Image: alpine:3.14
          Cpu: 256
          Memory: 512
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
              Protocol: tcp
      RequiresCompatibilities:
        - EC2
      NetworkMode: bridge
      Cpu: "256"
      Memory: "512"
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      PlacementConstraints:
        - Type: distinctInstance

  TaskDefinition2:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: task-definition-2
      ContainerDefinitions:
        - Name: container-2
          Image: alpine:3.14
          Cpu: 256
          Memory: 512
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
              Protocol: tcp
      RequiresCompatibilities:
        - EC2
      NetworkMode: bridge
      Cpu: "256"
      Memory: "512"
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      PlacementStrategy:
        - Type: binpack
          Field: cpu
      PlacementConstraints:
        - Type: distinctInstance

  Service1:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref TestCluster
      ServiceName: service-1
      TaskDefinition: !Ref TaskDefinition1
      DesiredCount: 3
      LaunchType: EC2
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - sg-0123456789abcdef0  
          Subnets:
            - subnet-0123456789abcdef0
            - subnet-0123456789abcdef1  

  Service2:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref TestCluster
      ServiceName: service-2
      TaskDefinition: !Ref TaskDefinition2
      DesiredCount: 3
      LaunchType: EC2
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - sg-0123456789abcdef0
          Subnets:
            - subnet-0123456789abcdef0
            - subnet-0123456789abcdef1  
