apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "myapp.fullname" . }}
  labels:
    app: myapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: myapp:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "myapp.fullname" . }}
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 80
