replicaCount: 3
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: true
  host: myapp.example.com
  annotations:
    kubernetes.io/ingress.class: nginx
